export { htmlNodeToIr, styledNodeToIrV2 } from './transform.js';
export type { TransformOptions } from './transform.js';

// Re-export all IR v2 types from shared
export type {
  // Core
  IrNode,
  SourceSpan,
  BreakpointCondition,
  AccessibilityMetadata,
  ResponsiveVariant,

  // ComputedStyle & primitives
  ComputedStyle,
  TextAlign,
  TextTransform,
  CssDimension,
  PositionType,
  Overflow,
  DisplayType,

  // SemanticIR & all role interfaces
  SemanticIR,
  ButtonSemantics,
  ButtonVariant,
  TextSemantics,
  TextType,
  HeadingSemantics,
  HeadingLevel,
  ImageSemantics,
  ImageFit,
  ImageLoading,
  IconSemantics,
  FormSemantics,
  FormField,
  InputSemantics,
  InputType,
  ValidationRules,
  TextareaSemantics,
  SelectSemantics,
  SelectOption,
  LinkSemantics,
  ListSemantics,
  ListItemSemantics,
  ListStyle,
  TableSemantics,
  TableColumn,
  TableRow,
  TableCell,
  DividerSemantics,
  DividerOrientation,
  SectionSemantics,
  NavSemantics,
  HeaderSemantics,
  FooterSemantics,
  ArticleSemantics,
  CardSemantics,
  DialogSemantics,
  TabContainerSemantics,
  TabItem,
  GenericSemantics,
  UnknownSemantics,

  // LayoutIR & all strategy interfaces
  LayoutIR,
  NoLayout,
  BoxLayout,
  BoxSizingMode,
  FlexLayout,
  FlexDirection,
  FlexWrap,
  MainAxisAlignment,
  CrossAxisAlignment,
  GridLayout,
  GridTrack,
  GridGap,
  GridAutoFlow,
  StackLayout,
  StackHorizontalAlignment,
  StackVerticalAlignment,
  StackFit,
  ScrollLayout,
  ScrollAxis,
  AbsoluteLayout,

  // TargetIR & platform hints
  TargetIR,
  FlutterHint,
  ComposeHint,
  SwiftUIHint,
  NamedArgument,

  // Type guards & helpers
  isSemanticRole,
  hasLayout,
  defaultAccessibility,
  emptySourceSpan,
  defaultComputedStyle,
  defaultTargetIR,
} from '@html-native/shared/ir-v2.js';
